### ISSUE TITLE
cannot find any Live Streaming Apps

### ISSUE THREAD

**Issue by 3dseals** [Mobcrush/ReplayKitDemo#1]
Hi @jgh- 
First, Thank you for the demo.
I would like to code a live streaming game such as [Go Live with ReplayKit](http://devstreaming.apple.com/videos/wwdc/2016/601nsio90cd7ylwimk9/601/601_go_live_with_replaykit.pdf).
I cannot find any Live Streaming Apps when i press Broadcast Button.
I use Xcode 8 beta and ios 10 iphone for test the Fox Demo,
and i have installed mobcrush app on my iphone.
Any other settings to make mobcrush app show?

**Comment by jgh-** [comment]
Hi @3dseals 

Our app (with the ReplayKit extension) is available via TestFlight for now (until iOS 10 is released), please email replaykitlive@mobcrush.com for access.
